### ISSUE TITLE
2018 Drive Train with Arcade Drive and CTRE Phoenix

### ISSUE THREAD

**Issue by DrewTheRat** [Mercury1089/2018-robot-code#1]
## Goal
Functional drivetrain subsystem that can be driven with two JoySticks using the Arcade Drive method
- Left Stick = Forward/Back speed
- Right Stick = Left/Right steering

We need to use Talson SRX motor controllers with mag encoders. Do not use RobotDrive class, as it can interfere with Talons in closed-loop mode
## Acceptance Criteria
- [x] CTRE Phoenix libraries added to 2018 project
- [x] Standalone ArcadeDrive helper class with methods copied from [RobotDrive source](https://github.com/wpilibsuite/allwpilib/blob/master/wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotDrive.java)
- [x] DriveTrain class (extends Subsystem) provides interface to Talons
- [x] DriveWithJoysticks command (extends Command) is the default command and implements the ArcadeDrive Joystick-driven control
- [x] Uses Talon SRX controllers via new CTRE Phoenix libraries
- [x] All IDs (e.g. for CAN) are defined in RobotMap class
- [x] JoyStick deadzone values in constants, single method used to apply deadzone value
- [x] Code drive-tested on 2017 robot (Crossfire)

**Comment by Endoman123** [comment]
Can we call this done?

**Comment by DrewTheRat** [comment]
I think we can call this done, yes.
