### ISSUE TITLE
Complex Trajectories Using Motion Profiles

### ISSUE THREAD

**Issue by DrewTheRat** [Mercury1089/2018-robot-code#10]
## Goal
Calculate and execute complex trajectories using motion profiles
## Acceptance Criteria
- [x] Ability to create trajectories using waypoints based on the 2018 field (i.e. Arcade)
- [ ] Ability to run these trajectories during auton using the Talon/Victor SRX drivetrain

## Tech Notes
This [CD Article](https://www.chiefdelphi.com/forums/showthread.php?t=156741) suggests generating paths and implement motion profiles using these:
1. [Pathfinder by Jaci](https://github.com/JacisNonsense/Pathfinder)  Supposed to be easy to follow integration guide provided in the Wiki
2. [TrajectoryLib by Team 254](https://github.com/Team254/TrajectoryLib) - No documentation :confused:
3. [SmoothPathPlanner by KHEngineering](https://github.com/KHEngineering/SmoothPathPlanner) - A follow-up to 254's TrajectoryLib with _a lot_ more documentation.

**Comment by SagarPatel201** [comment]
Tested and confirmed working, closed.
