### ISSUE TITLE
DriveDistance

### ISSUE THREAD

**Issue by DrewTheRat** [Mercury1089/2018-robot-code#11]
## Goal
DriveDistance command that uses an encoder and closed loop control on the Talon SRX to move the robot a specific distance
## Acceptance Criteria
- [x] DriveDistance command object constructed with a distance (in feet) and a max voltage
- [x] Encode positions published to the network table in feed and ticks
- [x] Uses the latest objects and methods from CTRE
- [x] DistanceProvider interface that can be implemented by other classes to provide a distance to the DriveDistance command.
- [x] Additional constructor that takes a DistanceProvider object and max voltage.
- [x] Initialize method gets the distance from the DistanceProvider if it there.
- [x] State of the controller should be the same after driving a given distance than it was prior to driving
- [x] DriveDistance exit condition should not prematurely be triggered when system is oscillating around target position

**Comment by DrewTheRat** [comment]
This should have been done days ago - getting it in here just to make sure we have everything working.

**Comment by Endoman123** [comment]
Closed since we have tested this with various values: hardcoded and sensor-fed.
