### ISSUE TITLE
RotateRelative

### ISSUE THREAD

**Issue by DrewTheRat** [Mercury1089/2018-robot-code#12]
## Goal
RotateRelative command object that rotates to a heading relative to its current rotation.
## Acceptance Criteria
- [x] RotateRelative class that takes the heading in the constructor and a PIDSource instance that provides the current heading
- [x] PIDSource object to provide the heading. _Note: This can be a gyro or NavX class if they implement PIDSource, otherwise we should create a wrapper._
- [x] One-line code change is all that is required to switch from analog gyro to NavX
- [x] Works against latest version of WPILIB released by the end of the build season

**Comment by SagarPatel201** [comment]
Done, closed.
