### ISSUE TITLE
Vision Processing - Cube Detection

### ISSUE THREAD

**Issue by DrewTheRat** [Mercury1089/2018-robot-code#13]
## Goal
Create vision processing code that can be deployed and run on the Raspberry Pi,

## Acceptable Criteria
- [x] Create vision pipeline that can recognize the zipper on the power cubes
- [x] Create streams for both camera input and painting target bounding box
- [x] Publish contours of the cube to the network table
- [x] Deploy and test on Raspberry Pi
- [x] Tune pipeline to work in most scenarios

**Comment by SagarPatel201** [comment]
Done, deprecated in favor of PixyCam.
