### ISSUE TITLE
Replace NetworkTable usage with NetworkTableInstance and NetworkTableEntry

### ISSUE THREAD

**Issue by DrewTheRat** [Mercury1089/2018-robot-code#14]
## Goal
Robot code uses new NetworkTableInstance and NetworkTableEntry functions with improved performance
## Acceptance Criteria
- [x] Remove any use of the now deprecated NetworkTable class and replace with NetworkTableInstance
- [x] Replace NetworkTable getter and setter usage with NetworkTableEntry getter/setter
- [x] Test getting and setting values by confirming they update in Outline Viewer and the Smart Dash
## Background
From @gartaud:
Screensteps has details on [New Network Table Classes](https://wpilib.screenstepslive.com/s/currentCS/m/getting_started/l/801080-new-for-2018#network-tables)

- API updated to provide handle-based access for improved performance. This also allows multiple simultaneous independent instances to be created (e.g. for unit testing purposes).
  - Added new classes and interfaces (NetworkTableInstance, NetworkTableEntry, NetworkTableValue, and others).  In Java, these, along with a new version of the NetworkTable class, are now located in a different package (edu.wpi.first.networktables, rather than edu.wpi.first.wpilibj.networktables)
  - The NetworkTable class is still available, but many functions are now deprecated in favor of NetworkTableInstance and NetworkTableEntry functions.
  - In Java, many JNI functions changed; it’s recommended users of the old JNI functions change to using NetworkTableInstance instead of JNI directly.
  - There is a “default” instance that is configured by the WPILib robot code during startup; this can be retrieved using NetworkTableInstance.getDefault().  You can then get NetworkTable’s by calling NetworkTableInstance.getTable(String).  This replaces the old NetworkTable.getTable() static function.
  - NetworkTableEntry’s are returned by NetworkTable.getEntry(String).  NetworkTableEntry provides functions for getting and setting values similar to the old NetworkTable string-based getters and setters, but is faster because it uses handles rather than string lookups.

So...
```
nt = NetworkTableInstance.getDefault().getTable(networktable);`
nt.getEntry("area").getDoubleArray(def)
```

**Comment by Endoman123** [comment]
As of 2c74dc06db70f7b046d89ac18a26279a4fc807cf, used in :robot.
As of 151aae04fbe631e2203c0aa68fb9418f5c85f63d, used in :vision.

Closed since all code is using latest NTCore classes.
