### ISSUE TITLE
Unit Conversions

### ISSUE THREAD

**Issue by Endoman123** [Mercury1089/2018-robot-code#17]
## GOAL
Implement unit conversions in the `MercMath` class

## ACCEPTABLE CRITIERIA
Must implement the following conversions (assume the inverse as well):
- [x] Centimeters to inches
- [x] Seconds to minutes
- [x] Minutes to hours
- [x] Move DriveTrain math to MercMath

**Comment by SagarPatel201** [comment]
Done a while ago, closed.
