### ISSUE TITLE
Create Sensor Class for Pixy Cam

### ISSUE THREAD

**Issue by DrewTheRat** [Mercury1089/2018-robot-code#20]
## Goal
Sensor class for the Pixy Cam connected to the RoboRio SPI port that will return coordinates.
## Acceptance Criteria
- [x] Sensor and supporting classes created for the Pixy Cam
- [x] Connection via the RoboRio SPI port (for now)
- [x] CenterX, CenterY, Width, Height for each detected object
- [x] Methods to pull the largest object
- [x] PID rotation using the Pixy Cam as the sensor instead of Gyro (rotate left or right until object centered)
- [x] Update sensor to use I2C
## Notes
Classes can probably be ported from here: https://github.com/croadfeldt/wpilib_pixy_spi_java

**Comment by Endoman123** [comment]
Notes: 
- 7 signature "profiles"
- Contour info signed as some hex(?) string; need to parse into ints
- Int info: Signature profile number, x, y, width, height, error code(?)
