### ISSUE TITLE
Code Autonomous

### ISSUE THREAD

**Issue by sriharis123** [Mercury1089/2018-robot-code#23]
## GOAL
Make auton motion profiles using paths and add auton logic in code

## ACCEPTANCE CRITERIA
- [x] Create and test all necessary profiles
- [x] Test possible autons

**Comment by DrewTheRat** [comment]
In generating the paths, keep in mind we will probably need to tweak them at our first competition, as that will be the first time we're on the actual field. We should make sure we are set up to update the paths quickly based on what we observe on the field.
