### ISSUE TITLE
Upgrade software (WPI lib, Phoenix framework) to latest version

### ISSUE THREAD

**Issue by gartaud** [Mercury1089/2018-robot-code#26]
## Goal
Update all software to the latest version
## Acceptance Critieria
- [ ] WPI lib should be upgraded to 2018.3.3 using Eclipse's "Help, Check for Updates" feature (https://github.com/wpilibsuite/allwpilib/releases/tag/v2018.3.3)
- [ ] Phoenix framework should be upgraded to at least Phoenix 5.2.2.0 to get rid of the sporadic error -63194 as described at https://github.com/CrossTheRoadElec/Phoenix-Documentation#driver-station-system-watchdog--63194-and-motor-controllers-not-enabling.
- [ ] Installer for Phoenix 5.2.2.0 can be found at http://www.ctr-electronics.com/control-system/hro.html#product_tabs_technical_resources

**Comment by DrewTheRat** [comment]
@Endoman123 Is there a way to do this automatically with GradleRIO? It should at least do it for WPI lib, right?

**Comment by Endoman123** [comment]
@DrewTheRat It's just a matter of changing the version number inside the WPIExtension instance in the project.
