### ISSUE TITLE
Consolidate and move all Talon settings to methods in DriveTrain

### ISSUE THREAD

**Issue by DrewTheRat** [Mercury1089/2018-robot-code#27]
## Goal
All settings are applied to Talons by methods in DriveTrain.
## Acceptance Criteria
- [x] Replace `DriveDistance.setPIDF()` and `MoveOnPath.configurePID()` with one method in `DriveTrain`.
- [x] Add `setNeutralMode( NeutralMode neutralMode)` method to `DriveTrain`. It should apply the specified NeutralMode value the two Talons and two Victors.
- [x] Set the neutral mode in all commands that require the drive train:
    - [x] DriveDistance
    - [x] DriveTank
    - [x] DriveArcade
    - [x] DriveWithLIDAR (_may not be required as this extends DriveDistance_)
    - [x] MoveOnPath
    - [x] RotateRelative
    - [x] RotateToTarget
- [ ] Remove getLeft() and getRight() accessors from DriveTrain or make them private.

**Comment by gartaud** [comment]
Maybe an extreme position, but I advocate removing getLeft() and getRight() accessors from DriveTrain to guarantee that all settings will indeed be applied by methods in DriveTrain.

**Comment by DrewTheRat** [comment]
@gartaud I think that's a good ideal. I added it to the acceptance criteria.
