### ISSUE TITLE
Do not directly call getGameSpecificMessage(). Always rely on GameData

### ISSUE THREAD

**Issue by gartaud** [Mercury1089/2018-robot-code#28]
## Goal
Always rely on GameData because the game specific message is a string that originates outside of the robot's code its contents should not be blindly trusted.
## Acceptance Criteria
- [x] Use GameData class go FMS game data wherever required.
The GameData class does a good job at parsing the string, and therefore should be relied upon whenever data about the game is needed.

**Comment by gartaud** [comment]
Make sure that the fact that updateDash() may be called before autonInit() is taken into consideration. You might want to add an update() or refresh() method that forces the refetching of the data to GameData and explicitly call it in autonInit() so that you don't end up using old data from the previous match...

**Comment by DrewTheRat** [comment]
Closing this because it is superseded by issue #31.
