### ISSUE TITLE
Document Auton Paths

### ISSUE THREAD

**Issue by DrewTheRat** [Mercury1089/2018-robot-code#3]
## Goal:
Field diagram that can be used to plan auton actions and code auton paths.
## Acceptance Criteria:
- [x] Field diagram showing potential auton paths with distances and turn angles calculated and labeled

**Comment by sriharis123** [comment]
Currently has 90 degree turn angles, as these values could be used for curve driving / motion profiling

**Comment by AarjavP** [comment]
my mistake, the previous two commits here have wrong issue number because i was trying to quickly push in the commits.
