### ISSUE TITLE
Basic Motion Profiling

### ISSUE THREAD

**Issue by DrewTheRat** [Mercury1089/2018-robot-code#7]
## Goal
Run a basic motion profile on the drive train using Talon SRXs
## Acceptance Criteria
- [x] Max RPM of drive train and Feed Forward value calculated properly
- [x] Simple straight-line motion profile runs as expected
- [x] Simple curve motion profile runs as expected

**Comment by DrewTheRat** [comment]
I updated this issue to make the goal more clear.

**Comment by Endoman123** [comment]
Tested and confirmed working, closed
