### ISSUE TITLE
Code Lidar Sensor

### ISSUE THREAD

**Issue by DrewTheRat** [Mercury1089/2018-robot-code#9]
## Goal
Lidar sensor class that can be used query a LIDAR Lite 3 connected to the RoboRio.
## Acceptance Criteria
- [x] LIDAR Lite 3 connected via PWM to a CTRE Canifier
- [x] Access Canifier via CTRE Phoenix classes
- [x] Class gets sensor value from PWM channel
- [x] Canifier should be set to should poll the LIDAR every 100 ms (should be the default)
## Technical Notes
[CTRE Canifier Documentation](http://www.ctr-electronics.com/downloads/pdf/CANifier%20User's%20Guide.pdf): includes details on connecting the LIDAR Lite
[LIDAR Lite Product Specs](http://files.andymark.com/PDFs/pli-06-instruction.pdf): From AndyMark
[CTRE Canifier Demo](https://github.com/CrossTheRoadElec/Phoenix-Examples-Languages/tree/master/Java/CANifier%20Demo): Shows example of connecting LIDAR Lite.

**Comment by DrewTheRat** [comment]
I have updated this issue now that we decided to use the Canifier.

**Comment by Endoman123** [comment]
Considering that we're using the LIDAR to cheese the robot, we can consider this done.
